### PR TITLE
disable default item buying

### PR DESCRIPTION
**Pull request by Nostrademous**
by using "item_purchase_generic" we disable bots from buying items by default.

You can also control a specific heroes behavior by creating a file called "item_purchase_<heroname>.lua" but we want our own control of item buying by RL.

### CODE REVIEW

**Comment by TimZaman** [comment]
Whats your opinion on using the `*_generic.lua` stuff? Seems like the current nevermore stuff isnt related to nevermore at all.

**Comment by Nostrademous** [comment]
It's useful to gut Valve defaults so you have full control of the bots. About it.

Unfortunately there isn't a bot_generic.lua.

Once we get into writing actual agents for various heroes I will have a lot of opinion, but for now I think we should focus on finalizing dotaservice, no?

And about Nevermore, honestly, I think OpenAI's approach is a bit wrong from a "generalization" point of view in how they train per hero specific. We should, at least I plan to anyways, implement RL behavior that's largely agnostic of any specific hero. I envision training the agents based on "turn rate, base movement speed, bounding box size, base attack speed, agi/str/int base + per level increment, base attack range, etc." as well as teach even abilities in a largely generic manner such as "it is an ability with this attack range, this cast point, this targeting behavior, this side effects (i.e., stun/silence/hex/etc.), this cooldown, this mana cost, etc.".

That way our bots will be fine in Ability Draft as well as normal game and we don't have to teach an agent per hero, but rather across the sleuth of generic abilities/items.

**Comment by TimZaman** [comment]
Docs say: "If you'd like to completely take over control of a hero, you can
implement a Think() function in a file called bot_generic.lua,"

**Comment by TimZaman** [comment]
And myself, i will never write a bot for a specific hero. I want the bots
to train stat stuff himself. People aren't very good at programming such
complicated behaviour, the only way to manage complexity is by letting it
solve itself.

>

**Pull request merged**
