### PR TITLE
working SF play against default Sniper mid

### PR DESCRIPTION
**Pull request by Nostrademous**
This PR forces the system to Play our SF agent against the DEFAULT sniper agent.

It is slightly unfair in the fact that Sniper will level abilities and buy items and get runes... etc. All the stuff we don't have implemented for SF yet, but it works.

### CODE REVIEW

**Comment by TimZaman** [comment]
Very cool. Dieing to get this kind of validation. We'll get to abilites and
items at some point. We should then see our baseline just get better and
better.

**Comment by TimZaman** [comment]
Hmmyeah but this hardcoded stuff isnt what we should want. We want to select heroes ourselves, then the dotaservice creates the right corresponding lua files

**Comment by Nostrademous** [comment]
Small steps. Let’s make sure this works and gives us what we need and I will add your request. Thinking about it, I will need my other PR merged to achieve what you want as it tells the python code what heroes were selected for what side.

**Comment by TimZaman** [comment]
Hmm this is a step back bc i could previously already do this, but i want
self play. I want 1:100 games to be a validation game against the default
bot though .

Whats interesting is that in the custom game you can pick a bot script per
side.. so i think that should be available in the cli api too

**Comment by Nostrademous** [comment]
If you are randomly determining the two heroes to be selected ahead of time (meaning not during hero selection) then your request is easy. If you want to do it as a counter-pick (meaning you need to see opponents selection first) then I need my other PR

**Comment by TimZaman** [comment]
I dont think we get to opponent selection any time soon. Not a prio i think

**Comment by TimZaman** [comment]
I don't think we want to route that this PR is going, as we already had this a few months ago, and doesn't allow for self-play. Closing in favour of the other.

**Pull request closed without merging**
