### PR TITLE
Getting Example/Client.py Running

### PR DESCRIPTION
**Pull request by Nostrademous**
So I'm running this as a test on my OSX box. I needed to make the following changes to get the examples/client.py up and running.

I still do have questions about where the config file exists and how to get it to render (apparently I should just be able to send the render=True in the config file, but not sure where the config is -- I realize it is a dotaservice protobuf construct but never seen it).

Also, a README on the order of operations dotaservice tries to execute would be beneficial I think as based on console messages it seems to try and run the C++ bots first, fails, then defaults to Lua scripts. It then tries to load the "team_desires.lua" which you haven't stubbed out yet, fails, but seems to continue.

I can fix the desires and such but would love some more explanation and perhaps even a pretrained model you might have. 

Perhaps we can setup a discord channel we can chat on or leave messages?

### CODE REVIEW

**Comment by TimZaman** [comment]
Aaah so you got it up and running already? Victory! How hard was it? Also
the example is just that, an example. Either it stays an example or should
be a package/github repo by itself.

**Comment by Nostrademous** [comment]
I mean it's not hard, it's code after all and you have the code to review/search as well as error/debug messages to guide you.

Things I missed (but you noted and I just missed b/c I skimmed in my reading):
* the fact I have to install steam
* the fact I have to install dota2

for both the above I just assumed that when the 20GB docker file is pulled down it would already have everything I need in it. I mean it became quickly apparent when trying to run dotaservice what was missing.

Everything else was either env differences or hard-coded variables that needed to be changed or extra pip packages I needed to install. I would hope anyone with some coding tradecraft and familiarity with OSes should be able to solve.

I will say I have not gotten the "rendering" to work yet. I would have thought it would be a parameter passed to dotaservice but currently it's not. Based on your other replies to lenLRX it seems like it should have worked (I even modified the default protobuf value to True for the Config, re-compiled the protobuf, restarted the dotaservice, and still no dice). 

Did you get my email I sent to timbobel@gmail.com or is that a throw-away?

**Comment by Nostrademous** [comment]
Oh, and to answer one of your questions from here: https://github.com/TimZaman/dotaservice/blob/master/examples/client.py#L221

I believe it is b/c certain abilities in the game attach to a unit and persist past the unit's death. For example, [Disruptor's Thunder Strike](https://dota2.gamepedia.com/Disruptor) is one. If the unit dies they can't garbage collect the unit as it would delete the attached ability effect (I mean they could if they implemented it different, but I don't think they care) so they keep the unit around until all debuffs on it are completed.

**Comment by TimZaman** [comment]
And yeah I'll host a pretrained model somewhere. It's remarkably good.

**Comment by TimZaman** [comment]
A lot of comments, I don't think there'll be much left of this MR XD

**Pull request closed without merging**
